import {
  LayoutDashboard,
  Users,
  Store,
  Footprints,
  ShoppingBag,
  Package,
  Factory,
  UserRound,
  IndianRupee,
  Wallet,
  HandCoins,
  CalendarClock,
  MapPin,
  BarChart3,
  Bell,
  History,
  Settings,
  Search,
  Share2,
  MessageCircle,
  Plus,
  Pencil,
  Download,
  SlidersHorizontal,
  MoreHorizontal,
  CheckCircle2,
  Hourglass,
  AlertTriangle,
  Truck,
  PackageCheck,
  Calendar,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Eye,
  Check,
  Building2,
  Phone,
  Mail,
  FileText,
  LogOut,
  Moon,
  Sun,
  Layers,
  ArrowUpRight,
  ArrowDownRight,
  RefreshCw,
  HelpCircle,
  Trash2,
  KeyRound,
  ShieldCheck,
  Percent,
  ExternalLink,
  Globe,
  Clock,
  ReceiptText,
  Send,
} from 'lucide-react';

export const Icons = {
  // Navigation & Core Entities
  Dashboard: LayoutDashboard,
  ExternalLink: ExternalLink,
  Globe: Globe,
  Clients: Users,
  Client: Users,
  Users: Users,
  Store: Store,
  Designs: Footprints,
  Catalogue: Footprints,
  Orders: ShoppingBag,
  Items: Package,
  Manufacturers: Factory,
  SalesTeam: UserRound,
  Payments: IndianRupee,
  Receivables: Wallet,
  Outstanding: Wallet,
  Collections: HandCoins,
  FollowUps: CalendarClock,
  Visits: MapPin,
  Reports: BarChart3,
  Notifications: Bell,
  AuditLog: History,
  Activity: History,
  Settings: Settings,

  // Actions & Controls
  Search: Search,
  Share: Share2,
  WhatsApp: MessageCircle,
  Add: Plus,
  Edit: Pencil,
  Export: Download,
  Filter: SlidersHorizontal,
  More: MoreHorizontal,
  Close: X,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  View: Eye,
  Eye: Eye,
  Check: Check,
  Delete: Trash2,
  Refresh: RefreshCw,
  Download: Download,
  ArrowLeft: ChevronLeft,
  Back: ChevronLeft,

  // Status & Indicators
  Approved: CheckCircle2,
  Pending: Hourglass,
  Overdue: AlertTriangle,
  Alert: AlertTriangle,
  AlertCircle: AlertTriangle,
  Dispatched: Truck,
  Delivered: PackageCheck,
  Date: Calendar,
  Calendar: Calendar,

  // Auxiliary
  Building: Building2,
  Phone: Phone,
  Mail: Mail,
  Document: FileText,
  FileText: FileText,
  Percent: Percent,
  Logout: LogOut,
  Moon: Moon,
  Sun: Sun,
  Layers: Layers,
  TrendingUp: ArrowUpRight,
  TrendingDown: ArrowDownRight,
  Help: HelpCircle,
  Security: ShieldCheck,
  Lock: ShieldCheck,
  Key: KeyRound,
  Clock: Clock,
  Success: CheckCircle2,
  Receipt: ReceiptText,
  Send: Send,
} as const;

export type IconName = keyof typeof Icons;
